#pragma once

// Generated by tools_local/gen_insider_words.py from tools_local/insider_words.txt.
// Do not edit.

#include <cstdint>

namespace insider {

// 560 words. Longest is 'CONSTELLATION' at 13 characters, which is what
// the reveal card is sized against.
inline constexpr int kWordCount = 560;
inline constexpr int kMaxWordLen = 13;

// constexpr, so the table and every string in it land in flash rather than
// being copied into the 380KB of DRAM at startup.
inline constexpr const char* kWords[kWordCount] = {
    "ACCORDION",  "ACORN",      "AIRPLANE",      "AIRPORT",    "ALLIGATOR",   "AMBULANCE",  "ANCHOR",
    "ANGEL",      "ANT",        "APPLE",         "ARMCHAIR",   "ARMOR",       "ARROW",      "ARTICHOKE",
    "ASTRONAUT",  "AVOCADO",    "AXE",           "BAGPIPE",    "BALLOON",     "BAMBOO",     "BANANA",
    "BANDAGE",    "BANNER",     "BARREL",        "BASEBALL",   "BASKET",      "BATTERY",    "BEACH",
    "BEACON",     "BEAR",       "BEARD",         "BED",        "BEETLE",      "BELL",       "BENCH",
    "BERRY",      "BICYCLE",    "BIRD",          "BLACKBOARD", "BLANKET",     "BLIZZARD",   "BLUEPRINT",
    "BOAT",       "BONE",       "BOOK",          "BOOKMARK",   "BOOMERANG",   "BOTTLE",     "BOULDER",
    "BOX",        "BRACELET",   "BRAIN",         "BREAD",      "BRIDGE",      "BROCCOLI",   "BRONZE",
    "BROOM",      "BRUSH",      "BUBBLE",        "BUCKET",     "BUFFALO",     "BUILDING",   "BULB",
    "BUMPER",     "BUS",        "BUTTERFLY",     "BUTTON",     "CACTUS",      "CAKE",       "CALENDAR",
    "CAMEL",      "CAMERA",     "CAMPFIRE",      "CANDLE",     "CANYON",      "CAR",        "CARAVAN",
    "CARPET",     "CARROT",     "CASTLE",        "CAT",        "CATHEDRAL",   "CELLAR",     "CENTIPEDE",
    "CHAIR",      "CHANDELIER", "CHEESE",        "CHICKEN",    "CHIMNEY",     "CHIPMUNK",   "CHOCOLATE",
    "CHURCH",     "CIRCLE",     "CIRCUS",        "CLARINET",   "CLIFF",       "CLIPBOARD",  "CLOCK",
    "CLOSET",     "CLOUD",      "CLOWN",         "COAT",       "COBWEB",      "COIN",       "COMET",
    "COMPASS",    "COMPUTER",   "CONSTELLATION", "COOKIE",     "CORAL",       "COTTAGE",    "COW",
    "CRAB",       "CRADLE",     "CRICKET",       "CROCODILE",  "CROSSBOW",    "CROWN",      "CRYSTAL",
    "CUCUMBER",   "CUP",        "CURTAIN",       "CYCLONE",    "DAGGER",      "DAISY",      "DANDELION",
    "DEER",       "DESERT",     "DESK",          "DIAMOND",    "DICE",        "DINOSAUR",   "DOG",
    "DOLPHIN",    "DONKEY",     "DOOR",          "DOORBELL",   "DOVE",        "DRAGON",     "DRAWER",
    "DRESS",      "DRILL",      "DRUM",          "DUCK",       "EAGLE",       "EAR",        "EARRING",
    "EARTH",      "ECHO",       "ECLIPSE",       "EEL",        "EGG",         "ELEPHANT",   "ELEVATOR",
    "EMERALD",    "ENGINE",     "ENVELOPE",      "ERASER",     "EXPEDITION",  "EYE",        "EYEGLASSES",
    "FACE",       "FALCON",     "FAN",           "FEATHER",    "FENCE",       "FERRET",     "FESTIVAL",
    "FIELD",      "FIRE",       "FIREFLY",       "FIREPLACE",  "FIREWORK",    "FISH",       "FJORD",
    "FLAG",       "FLAMINGO",   "FLASHLIGHT",    "FLOWER",     "FLUTE",       "FOREST",     "FORK",
    "FORTRESS",   "FOSSIL",     "FOUNTAIN",      "FOX",        "FRACTION",    "FRAME",      "FREEZER",
    "FROG",       "FURNITURE",  "GALAXY",        "GARAGE",     "GARDEN",      "GARLIC",     "GAZELLE",
    "GEAR",       "GEYSER",     "GHOST",         "GIANT",      "GIFT",        "GIRAFFE",    "GLACIER",
    "GLASS",      "GLOBE",      "GLOVE",         "GLUE",       "GOAT",        "GOLDFISH",   "GONDOLA",
    "GORILLA",    "GRAPE",      "GRASSHOPPER",   "GRAVEYARD",  "GREENHOUSE",  "GRIFFIN",    "GUITAR",
    "HAMMER",     "HAND",       "HARBOR",        "HARMONICA",  "HARP",        "HAT",        "HAYSTACK",
    "HEART",      "HEDGEHOG",   "HELICOPTER",    "HELMET",     "HIGHWAY",     "HILL",       "HIPPO",
    "HONEYCOMB",  "HORIZON",    "HORSE",         "HOURGLASS",  "HOUSE",       "HURRICANE",  "ICE",
    "ICICLE",     "IGLOO",      "INKWELL",       "INSTRUMENT", "ISLAND",      "IVORY",      "JACKET",
    "JAGUAR",     "JAR",        "JELLYFISH",     "JEWEL",      "JIGSAW",      "JOURNAL",    "JUNGLE",
    "KANGAROO",   "KETTLE",     "KEY",           "KEYBOARD",   "KINGFISHER",  "KITE",       "KNIFE",
    "KNOT",       "KOALA",      "LABYRINTH",     "LADDER",     "LAGOON",      "LAMP",       "LANTERN",
    "LASSO",      "LAVA",       "LAWN",          "LEAF",       "LEMON",       "LEOPARD",    "LETTUCE",
    "LIBRARY",    "LIGHTHOUSE", "LIGHTNING",     "LION",       "LIZARD",      "LOBSTER",    "LOCK",
    "LOCOMOTIVE", "LOLLIPOP",   "LOOM",          "LUGGAGE",    "LUTE",        "LYNX",       "MACHINE",
    "MAGIC",      "MAILBOX",    "MAMMOTH",       "MANSION",    "MAP",         "MARBLE",     "MARKETPLACE",
    "MASK",       "MEADOW",     "MEDAL",         "MEGAPHONE",  "METEOR",      "MICROSCOPE", "MILL",
    "MIRAGE",     "MIRROR",     "MOAT",          "MONKEY",     "MONUMENT",    "MOON",       "MOSQUITO",
    "MOTORCYCLE", "MOUNTAIN",   "MOUSE",         "MUFFIN",     "MULE",        "MUMMY",      "MUSEUM",
    "MUSHROOM",   "NAIL",       "NARWHAL",       "NECKLACE",   "NECTAR",      "NEEDLE",     "NEST",
    "NET",        "NEWS",       "NINJA",         "NOTEBOOK",   "OASIS",       "OBOE",       "OBSERVATORY",
    "OCEAN",      "OCTOPUS",    "ONION",         "OPERA",      "ORANGE",      "ORCHARD",    "ORGAN",
    "OSTRICH",    "OTTER",      "OVEN",          "OWL",        "PADDLE",      "PALACE",     "PANDA",
    "PANTHER",    "PAPER",      "PARACHUTE",     "PASSPORT",   "PATH",        "PAW",        "PEACOCK",
    "PEARL",      "PEBBLE",     "PENCIL",        "PENGUIN",    "PEPPER",      "PERISCOPE",  "PETAL",
    "PHANTOM",    "PHOENIX",    "PIANO",         "PICKAXE",    "PICTURE",     "PIE",        "PIER",
    "PIG",        "PILGRIM",    "PILLAR",        "PILLOW",     "PINE",        "PINECONE",   "PIPELINE",
    "PIRATE",     "PISTOL",     "PITCHER",       "PIZZA",      "PLANET",      "PLANT",      "PLATE",
    "PLATYPUS",   "PLAZA",      "PLIERS",        "POCKET",     "POLAR",       "PONY",       "PORCUPINE",
    "PORTRAIT",   "POTION",     "PRAIRIE",       "PRESENT",    "PRISM",       "PUMPKIN",    "PUZZLE",
    "PYRAMID",    "QUAIL",      "QUARRY",        "QUARTZ",     "QUEEN",       "QUICKSAND",  "QUILL",
    "RABBIT",     "RACCOON",    "RADAR",         "RADIO",      "RAILWAY",     "RAINBOW",    "RAVEN",
    "REEF",       "RHINOCEROS", "RIDDLE",        "RIFLE",      "RING",        "RIVER",      "ROADMAP",
    "ROBOT",      "ROCKET",     "ROOSTER",       "ROPE",       "ROSE",        "RUBY",       "RUNWAY",
    "SADDLE",     "SAFARI",     "SAILBOAT",      "SALMON",     "SANDWICH",    "SAPPHIRE",   "SATELLITE",
    "SAUSAGE",    "SAXOPHONE",  "SCARECROW",     "SCEPTER",    "SCISSORS",    "SCORPION",   "SEAGULL",
    "SEAHORSE",   "SEAL",       "SEARCHLIGHT",   "SEASHELL",   "SERPENT",     "SHADOW",     "SHAMPOO",
    "SHARK",      "SHEEP",      "SHELL",         "SHIELD",     "SHIP",        "SHIPYARD",   "SHOE",
    "SHOVEL",     "SHRINE",     "SIDEWALK",      "SKELETON",   "SKYSCRAPER",  "SLOTH",      "SNAIL",
    "SNAKE",      "SNOWFLAKE",  "SNOWMAN",       "SOAP",       "SOCK",        "SOCKET",     "SOFA",
    "SPACESHIP",  "SPHINX",     "SPIDER",        "SPIRAL",     "SPONGE",      "SPOON",      "SPOTLIGHT",
    "SQUIRREL",   "STABLE",     "STADIUM",       "STAIRCASE",  "STAR",        "STATUE",     "STETHOSCOPE",
    "STINGRAY",   "STORK",      "STRAWBERRY",    "SUBMARINE",  "SUBWAY",      "SUN",        "SUNDIAL",
    "SUNFLOWER",  "SWAMP",      "SWAN",          "SWORD",      "TABLE",       "TAMBOURINE", "TANK",
    "TEAPOT",     "TELESCOPE",  "TEMPLE",        "TENT",       "THERMOMETER", "THRONE",     "THUNDER",
    "TICKET",     "TIGER",      "TOOLBOX",       "TORNADO",    "TOTEM",       "TOWER",      "TRACTOR",
    "TRAIN",      "TRAPEZE",    "TREADMILL",     "TREASURE",   "TREE",        "TRIANGLE",   "TROMBONE",
    "TROPHY",     "TRUCK",      "TRUMPET",       "TUNNEL",     "TURTLE",      "TYPEWRITER", "UMBRELLA",
    "UNICORN",    "UNIFORM",    "UNIVERSE",      "VALLEY",     "VAMPIRE",     "VASE",       "VILLAGE",
    "VINEYARD",   "VIOLIN",     "VOLCANO",       "VULTURE",    "WAGON",       "WALRUS",     "WAREHOUSE",
    "WARRIOR",    "WASP",       "WATCH",         "WATERFALL",  "WATERMELON",  "WELL",       "WHALE",
    "WHISTLE",    "WINDMILL",   "WINDOW",        "WING",       "WITCH",       "WIZARD",     "WOLF",
    "WOODPECKER", "WORKSHOP",   "WORM",          "WRENCH",     "YACHT",       "YARD",       "YEAST",
    "YETI",       "YOGURT",     "YOLK",          "ZEBRA",      "ZEPPELIN",    "ZOMBIE",     "ZOO",
};

}  // namespace insider
