import os
import re
import sys

# PlatformIO runs this script via exec() (no __file__); use project dir when set.
REPO_ROOT = os.environ.get("PLATFORMIO_PROJECT_DIR", os.getcwd())
SRC_DIR = os.path.join(REPO_ROOT, "src")

# Embedded /js → PROGMEM headers (same pre-step as HTML so CI / gh_release always has includes).
JS_EMBEDS = [
    ("data/js/inx_font_pack.js", "src/network/html/InxFontPackJs.generated.h", "INX_FONT_PACK_JS", "INXFP"),
    ("data/js/jszip.min.js", "src/network/html/JsZipMinJs.generated.h", "JSZIP_MIN_JS", "INXJZ9"),
    ("data/js/epub_page.js", "src/network/html/EpubPageJs.generated.h", "EPUB_PAGE_JS", "INXEPUB"),
    ("data/js/files_page.js", "src/network/html/FilesPageJs.generated.h", "FILES_PAGE_JS", "INXFILES"),
    ("data/js/library_page.js", "src/network/html/LibraryPageJs.generated.h", "LIBRARY_PAGE_JS", "INXLIB"),
]


def minify_html(html: str) -> str:
    # Tags where whitespace should be preserved
    preserve_tags = ['pre', 'code', 'textarea', 'script', 'style']
    preserve_regex = '|'.join(preserve_tags)

    # Protect preserve blocks with placeholders
    preserve_blocks = []

    def preserve(match):
        preserve_blocks.append(match.group(0))
        return f"__PRESERVE_BLOCK_{len(preserve_blocks)-1}__"

    html = re.sub(rf'<({preserve_regex})[\s\S]*?</\1>', preserve, html, flags=re.IGNORECASE)

    # Remove HTML comments
    html = re.sub(r'<!--.*?-->', '', html, flags=re.DOTALL)

    # Collapse all whitespace between tags
    html = re.sub(r'>\s+<', '><', html)

    # Collapse multiple spaces inside tags
    html = re.sub(r'\s+', ' ', html)

    # Restore preserved blocks
    for i, block in enumerate(preserve_blocks):
        html = html.replace(f"__PRESERVE_BLOCK_{i}__", block)

    return html.strip()


def write_js_header(js_path: str, out_path: str, array_name: str, delim: str) -> None:
    if not os.path.isfile(js_path):
        print(f"build_html: ERROR missing {js_path}", file=sys.stderr)
        sys.exit(1)

    with open(js_path, "r", encoding="utf-8") as f:
        body = f.read()

    close_seq = f"){delim}"
    if close_seq in body:
        print(f"build_html: ERROR {js_path} contains forbidden {close_seq!r}", file=sys.stderr)
        sys.exit(1)

    out_abs = os.path.join(REPO_ROOT, out_path)
    os.makedirs(os.path.dirname(out_abs), exist_ok=True)
    with open(out_abs, "w", encoding="utf-8") as h:
        h.write("// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY\n\n")
        h.write("#pragma once\n\n")
        h.write("#include <Arduino.h>\n\n")
        h.write(f'constexpr char {array_name}[] PROGMEM = R"{delim}(')
        h.write(body)
        h.write(f'){delim}";\n')

    print(f"Generated: {out_abs} ({len(body.encode('utf-8'))} bytes)")


def generate_embedded_js() -> None:
    for rel_js, rel_out, array_name, delim in JS_EMBEDS:
        js_path = os.path.join(REPO_ROOT, rel_js)
        write_js_header(js_path, rel_out, array_name, delim)


for root, _, files in os.walk(SRC_DIR):
    for file in files:
        if file.endswith(".html"):
            html_path = os.path.join(root, file)
            with open(html_path, "r", encoding="utf-8") as f:
                html_content = f.read()

            # minified = regex.sub("\g<1>", html_content)
            minified = minify_html(html_content)
            base_name = f"{os.path.splitext(file)[0]}Html"
            header_path = os.path.join(root, f"{base_name}.generated.h")

            with open(header_path, "w", encoding="utf-8") as h:
                h.write(f"// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY\n\n")
                h.write(f"#pragma once\n")
                h.write(f'constexpr char {base_name}[] PROGMEM = R"rawliteral({minified})rawliteral";\n')

            print(f"Generated: {header_path}")

generate_embedded_js()
